Repository rsksmart/rif-scheduler-services, pull requests merged in 2021-06, with the labels that each got.

#32 Update ci.yml
  .github/workflows/ci.yml
Labels: documentation

#34 run docker with node user
  .github/workflows/ci.yml
  Dockerfile
  package.json
Labels: bug

#37 Update README.md
  README.md
Labels: bug, documentation

#46 Renames
  .eslintrc.json
  src/Core.ts
  src/entities/Events.ts
  src/entities/Execution.ts
  src/entities/ScheduledExecution.ts
  src/entities/index.ts
  src/model/Collector.ts
  src/model/Executor.ts
  src/model/listeners/ListenerBase.ts
  src/model/recoverers/BatchRecoverer.ts
  src/model/recoverers/Recoverer.ts
  src/scripts/createCoreInstance.ts
  src/scripts/sendBalanceToProviderAccount.ts
  src/scripts/setupContracts.ts
  src/storage/Cache.ts
  src/storage/createDbConnection.ts
  test/Cache.test.ts
  test/Collector.test.ts
  test/CoreRunner.ts
  test/Executor.test.ts
  test/Recoverer.test.ts
  test/constants.ts
  test/mocks.ts
Labels: refactor

#45 Refactor Executor
  .eslintrc.json
  src/Core.ts
  src/entities/Events.ts
  src/entities/Execution.ts
  src/entities/ScheduledExecution.ts
  src/entities/index.ts
  src/model/Collector.ts
  src/model/Executor.ts
  src/model/listeners/ListenerBase.ts
  src/model/recoverers/BatchRecoverer.ts
  src/model/recoverers/Recoverer.ts
  src/scripts/createCoreInstance.ts
  src/scripts/sendBalanceToProviderAccount.ts
  src/scripts/setupContracts.ts
  src/storage/Cache.ts
  src/storage/createDbConnection.ts
  test/Cache.test.ts
  test/Collector.test.ts
  test/CoreRunner.ts
  test/Executor.test.ts
  test/Recoverer.test.ts
  test/constants.ts
  test/mocks.ts
Labels: refactor

#44 Add BatchRecoverer
  .eslintrc.json
  src/Core.ts
  src/entities/Events.ts
  src/entities/Execution.ts
  src/entities/ScheduledExecution.ts
  src/entities/index.ts
  src/model/Collector.ts
  src/model/Executor.ts
  src/model/index.ts
  src/model/listeners/ListenerBase.ts
  src/model/recoverers/BatchRecoverer.ts
  src/model/recoverers/Recoverer.ts
  src/model/recoverers/index.ts
  src/scripts/createCoreInstance.ts
  src/scripts/sendBalanceToProviderAccount.ts
  src/scripts/setupContracts.ts
  src/storage/Cache.ts
  src/storage/createDbConnection.ts
  test/Cache.test.ts
  test/Collector.test.ts
  test/CoreRunner.ts
  test/Executor.test.ts
  test/Recoverer.test.ts
  test/constants.ts
  test/mocks.ts
Labels: refactor
